name: Kernel Module CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel_version: [5.15.0-73-generic]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install kernel headers
      run: sudo apt-get install -y linux-headers-${{ matrix.kernel_version }}
    - name: Build kernel module
      run: make -C /lib/modules/${{ matrix.kernel_version }}/build M=$(pwd) modules
    - name: Load kernel module
      run: sudo insmod hello_world.ko
    - name: Unload kernel module
      run: sudo rmmod hello_world.ko
